build.yml modified

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -30,5 +30,44 @@ jobs:
         distribution: 'temurin'
     - name: Gradlew clean
       run: ./gradlew clean
+    - name: Gradlew test run
+      id: test
+      run: ./gradlew test
+    - name: Test check
+      run: |
+        if [[ ${{ steps.test.output.status }} != *"True"* ]]; then
+          echo "Tests run failed"
+          exit 1
+        fi
+        echo "All right -_-"
+    - name: Send alert in Telegram
+      if: ${{ failure() }}
+      uses: appleboy/telegram-action@master
+      with:
+        to: ${{ secrets.TELEGRAM_ME }}
+        token: ${{ secrets.TELEGRAM_NOT }}
+        message: |
+          ❌ Failed to build
+
     - name: Gradlew build bootable jar
-      run: ./gradlew build
+      run: ./gradlew bootJar
+
+    - name: Install RailwayCLI
+      run: npm i -g @railway/cli
+
+    - name: Deploy to Railway
+      id: deploy
+      run: railway up
+      env:
+        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
+
+    - name: Print railway status
+      run: echo ${{ steps.deploy.output.status }}
+
+    - name: Successful build
+      uses: appleboy/telegram-action@master
+      with:
+        to: ${{ secrets.TELEGRAM_ME }}
+        token: ${{ secrets.TELEGRAM_NOT }}
+        message: |
+          ✔ Application build done
